### ISSUE TITLE
Unable to free allocated memory in MemImage when resizing window due to critical change in gpu_allocator

### ISSUE THREAD

**Issue by bonohub13** [nikitablack/rust_vulkan_teapot#2]
gpu_allocator removed `Clone` from `gpu_allocator::vulkan::Allocation` since [release v0.16.0](https://github.com/Traverse-Research/gpu-allocator/compare/0.15.1...0.16.0) due to [this issue](https://github.com/Traverse-Research/gpu-allocator/issues/97).

Due to this change, it is not possible to free the memory allocation for the depth buffer image safely.

**Comment by nikitablack** [comment]
I have updated all dependencies to the latest versions for today. Changes can be observed in [this commit](https://github.com/nikitablack/rust_vulkan_teapot/commit/05806b9bd590853cf9a5b9b8a52d26adc0b76177).

**Comment by bonohub13** [comment]
@nikitablack Thank you!
